export const GET_GRAPH_DATA = 'GET_GRAPH_DATA'
export const GET_GRAPH_DATA_SUCCESS = 'GET_GRAPH_DATA_SUCCESS'
export const GET_GRAPH_DATA_FAILURE = 'GET_GRAPH_DATA_FAILURE'

export const GET_ANALYTICS_DATA = 'GET_ANALYTICS_DATA'
export const GET_ANALYTICS_SUCCESS = 'GET_ANALYTICS_DATA_SUCCESS'
export const GET_ANALYTICS_FAILURE = 'GET_ANALYTICS_DATA_FAILURE'